fieldLayouts:
  8fb23d71-31ba-4f3e-b4ce-57086fc29873:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 846afe8b-d10f-4235-b1c2-8f0d11cdf786
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 849d8a16-b71c-43bf-9ad3-98f0f07d495d # rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc4bae9c-6c1f-4926-9a93-2dd801898645
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09a15875-89d7-4c1b-8e0d-f0334da85203
        userCondition: null
handle: aboutUs
hasTitleField: false
name: 'about us'
section: a3aebb59-a9c2-4123-9aa4-012ef8bcae44 # about us
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
