fieldLayouts:
  397c2066-6f4a-4de3-ac59-71691d83624b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ac9a8b1a-cab0-412b-addc-54cc85c14c0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 000fde8f-92fe-4af7-abe8-6446a34ec616 # color code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 591da0a7-9a31-4883-8434-f27b70d0d733
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62c377a0-eb1e-4287-97a4-78011ebbf58c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 69a1934f-0fcc-4859-893c-0295510b65bf # color filters
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
