fieldLayouts:
  3e42df61-b3b0-4838-a268-5f2ba146f119:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 20a2513f-6b4a-49e9-8029-bbff3069f2f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 181ef542-5372-4d46-97bb-5e9f2cdb47c0
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a4bc6f82-e2be-4f2d-aa6c-e09db601a979 # demographic filters
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
