fieldLayouts:
  2299cdfe-f4c9-4a3f-83e7-bf5e3cff7607:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 28517f42-5257-4fe4-8aec-b242ef264966
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05c31966-53b6-4747-bae2-2a8801c6f6d7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 076b9e73-531b-4228-86a2-b4d74a5a565e # type filters
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
