fieldLayouts:
  aa180850-6c2f-43a2-9914-94aa0e48bb75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 72525358-8d73-4617-8140-961b38e5605f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 780c595f-5f5c-4621-ae7f-88e28c4d59fc # social icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5170cc3-5518-4e16-9caa-cf2ca4522215
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93afc15d-e2f3-4ac4-a984-53effc076090
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5c215a5d-b23b-4057-bf1a-ea37fd9522f8 # socials
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
