fieldLayouts:
  67d0137a-24cb-4126-b2fd-dbb8af425fd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d5bb6ca-4ec1-4a5e-a569-d2b27f1d3c9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 849d8a16-b71c-43bf-9ad3-98f0f07d495d # rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6a5984d-b277-41a4-8af5-c6bfc00d17c4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7aad3e0c-7cd2-4aac-8e35-cf08effc81ce
        userCondition: null
handle: heading
hasTitleField: false
name: heading
section: 70699232-1120-4f6c-86d3-51af3978bde5 # heading
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
