columnSuffix: zfgchrqs
contentColumnType: char(7)
fieldGroup: 12a23e1e-d239-4fe3-a9d8-4dbdb167eaea # Common
handle: colorCode
instructions: null
name: 'color code'
searchable: false
settings:
  defaultColor: '#ffffff'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
