columnSuffix: mncvmhbo
contentColumnType: text
fieldGroup: 12a23e1e-d239-4fe3-a9d8-4dbdb167eaea # Common
handle: number
instructions: null
name: number
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
