defaultPlacement: end
enableVersioning: true
handle: catalog
name: catalog
propagationMethod: all
siteSettings:
  e79be201-6bfa-4c8d-82e2-cfb8455ee223: # StienoShoes
    enabledByDefault: true
    hasUrls: true
    template: catalog/_entry
    uriFormat: 'catalog/{slug}'
type: channel
