defaultPlacement: end
enableVersioning: true
handle: heading
name: heading
propagationMethod: all
siteSettings:
  e79be201-6bfa-4c8d-82e2-cfb8455ee223: # StienoShoes
    enabledByDefault: true
    hasUrls: true
    template: heading/_entry
    uriFormat: heading
type: single
