defaultPlacement: end
enableVersioning: true
handle: products
name: products
propagationMethod: all
siteSettings:
  e79be201-6bfa-4c8d-82e2-cfb8455ee223: # StienoShoes
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: 'products/{slug}'
type: channel
