defaultPlacement: end
enableVersioning: true
handle: socials
name: socials
propagationMethod: all
siteSettings:
  e79be201-6bfa-4c8d-82e2-cfb8455ee223: # StienoShoes
    enabledByDefault: true
    hasUrls: true
    template: socials/_entry
    uriFormat: 'socials/{slug}'
type: channel
